### PR TITLE
Fixed Issue 39

### PR DESCRIPTION
**Pull request by MomoMiles**
#39 Fixed with the issues suggested fix. Seems to work fine for me.

### CODE REVIEW

**Comment by Malix-Labs** [comment]
@MomoMiles change the title to "`Fix #39`" please _😊_ _(this will have the effect of bouding [this PR](#40) to #39 and closing it in the meantime while logging it nicely in GitHub)_

**Comment by rexkix** [comment]
1. It appears that the PR only changes one instance of this line at 819. As the comment above indicates, there is a second instance at 833. Changing the one line did not help, but changing both did.

2. The "{{ 2:00 pm }}" trick doesn't work with this fix. I have to use the menus.

Please understand that I am a novice at this stuff. Thanks.
Did I do that right Malix?

**Comment by Malix-Labs** [comment]
> Did I do that right @Malix-Off?

Lol, yes 👍
I found it important to let the PR author know what you've found 😄

**Review by Malix-Labs — CHANGES_REQUESTED** [review]
In [this comment by @rexkix](https://github.com/Taimoor-Tariq/BetterDiscordStuff/pull/40#issuecomment-1133952691), it is been stated that :

> [...] [The PR](#40) only [changes one instance of this line at 819](https://github.com/Taimoor-Tariq/BetterDiscordStuff/pull/40/files#diff-40f32f42da22c40bf72266383f03a0677b3a7d597414d76272405ef6c98765d8R819).
[...] There is a second instance at [line 833](https://github.com/Taimoor-Tariq/BetterDiscordStuff/pull/40/files#diff-40f32f42da22c40bf72266383f03a0677b3a7d597414d76272405ef6c98765d8L833).
_Changing the one line did not help, but changing both did._

**Comment by Malix-Labs** [comment]
I made [a PR](https://github.com/MomoMiles/BetterDiscordStuff/pull/1) that correct [that](https://github.com/Taimoor-Tariq/BetterDiscordStuff/pull/40#pullrequestreview-981007186) : https://github.com/MomoMiles/BetterDiscordStuff/pull/1

**Comment by Malix-Labs** [comment]
> I made [a PR](https://github.com/MomoMiles/BetterDiscordStuff/pull/1) that correct [that](https://github.com/Taimoor-Tariq/BetterDiscordStuff/pull/40#pullrequestreview-981007186) : [MomoMiles#1](https://github.com/MomoMiles/BetterDiscordStuff/pull/1)

Too late, i'm making a new one.

**Comment by Malix-Labs** [comment]
> Too late, i'm making a new one.

#44

**Comment by Malix-Labs** [comment]
@Taimoor-Tariq any reason for the close?

**Comment by Taimoor-Tariq** [comment]
Going to rewrite the plugin acording to the new BetterDiscord API

**Comment by Malix-Labs** [comment]
- [Comment Reply](https://github.com/Taimoor-Tariq/BetterDiscordStuff/pull/40#issuecomment-1181294777) from @Taimoor-Tariq:
> Going to rewrite the plugin acording to the new BetterDiscord API

Ok, nice.
Could you create an issue about that so I can subscribe to its follow-up?

**Pull request closed without merging**
